### ISSUE TITLE
Make easily visible the distinction between item name and rating

### ISSUE THREAD

**Issue by chamakits** [rstolper/rateeverything#12]
You can either use a table or something else, to distinguish easily item name and rating.

**Comment by rstolper** [comment]
@chamakits Ratings are styled as colored icons in commit f64b0e7cd1284108698c680aaf7beb7650978aa5 
Can this issue be closed?

**Comment by chamakits** [comment]
Yup.
I'd personally like the icons to be slightly bigger than the text, but just a preference thing.
